version: '3.8'

services:
  angular-energy-app-client:
    build:
      context: .
      dockerfile: Dockerfile
    image: twotanawin/angular-energy-app-client:0.5 # Replace with your Docker Hub username
    ports:
      - "8084:80" # Maps the container's port 80 to your local machine's port 8084
    restart: always # Automatically restart the container if it crashes
